In [3]:
import cv2
import matplotlib.pyplot as plt
import numpy as np
# %matplotlib inline
# img=cv2.imread("2.jpg")
# asda
#dadsa

In [2]:
img

array([[[248,  62, 124],
        [248,  62, 124],
        [248,  62, 124],
        ...,
        [197, 224, 237],
        [197, 224, 237],
        [197, 224, 237]],

       [[248,  62, 124],
        [248,  62, 124],
        [248,  62, 124],
        ...,
        [197, 224, 237],
        [197, 224, 237],
        [197, 224, 237]],

       [[248,  62, 124],
        [248,  62, 124],
        [248,  62, 124],
        ...,
        [197, 224, 237],
        [197, 224, 237],
        [197, 224, 237]],

       ...,

       [[ 43,   3,   3],
        [ 43,   3,   3],
        [ 43,   3,   3],
        ...,
        [  4,   5,  60],
        [  4,   5,  60],
        [  4,   5,  60]],

       [[ 43,   3,   3],
        [ 43,   3,   3],
        [ 43,   3,   3],
        ...,
        [  4,   5,  60],
        [  4,   5,  60],
        [  4,   5,  60]],

       [[ 43,   3,   3],
        [ 43,   3,   3],
        [ 43,   3,   3],
        ...,
        [  4,   5,  60],
        [  4,   5,  60],
        [  4,   5,  60]]

In [16]:
cv2.imshow("image",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
def cv_show(name, img):
    cv2.imshow(name, img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [14]:
img.shape

(2989, 2802, 3)

In [23]:
img1 = cv2.imread("2.jpg",cv2.IMREAD_GRAYSCALE)
img1

array([[117, 117, 117, ..., 229, 229, 225],
       [117, 117, 117, ..., 206, 188, 170],
       [117, 117, 139, ..., 170, 170, 170],
       ...,
       [ 46,  46,  46, ...,  84,  84,  84],
       [ 46,  46,  46, ...,  84,  84,  84],
       [ 46,  46,  46, ...,  84,  84,  84]], dtype=uint8)

In [25]:
img1.shape

(2989, 2802)

In [27]:
cv_show("he",img)

In [4]:
vc = cv2.VideoCapture("nba.mp4")

In [5]:
if vc.isOpened():
    open , frame = vc.read()
else:
    open = False

In [9]:
while open:
    ret , frame = vc.read()
    if frame is None:
        break
    if ret == True:
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        cv2.imshow("result",gray)
        if cv2.waitKey(100) & 0xFF == 27:
            break
vc.release()
cv2.destroyAllWindows()

In [15]:
img = cv2.imread("1.png")
rick = img[1800:4000,1800:4000]
cv_show("rick",rick)

In [16]:
b,g,r = cv2.split(img)
b

array([[248, 248, 248, ..., 197, 197, 197],
       [248, 248, 248, ..., 197, 197, 197],
       [248, 248, 248, ..., 197, 197, 197],
       ...,
       [ 43,  43,  43, ...,   4,   4,   4],
       [ 43,  43,  43, ...,   4,   4,   4],
       [ 43,  43,  43, ...,   4,   4,   4]], dtype=uint8)

In [20]:
cv_show("b",b)

In [21]:
img = cv2.merge((b,g,r))
img.shape

(4500, 8000, 3)

In [22]:
#  只保留r
# 其余0，1，都设置为了0，所以为红颜色的了 
copy = img.copy()
copy[:,:,0] = 0
copy[:,:,1] = 1
cv_show("",copy)

In [26]:
img2 = cv2.resize(img,(500,500))
img2.shape
cv_show("",img2)

In [1]:
import cv2

# 开始计时
start = cv2.getTickCount()

# 读入一张图片
img = cv2.imread('lena.jpg')

# 停止计时
end = cv2.getTickCount()

# 单位：s
print((end - start) / cv2.getTickFrequency())

0.0102405
